name: End-to-end tests

on: 

  pull_request: 
    branches:
      - '**'
      
  push:
    branches:
      - '**' 

  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: "Qual navegador você vai realizar os testes"
        required: true
        options:
          - chromium
          - chrome
          - firefox
          - edge
          - webkit
          - electron

jobs:

  menu-test:

    runs-on: ubuntu-latest

    steps:
      
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

       # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm ci
     
      # Step 3: Configure node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '22.x'

      # Step 4: Execute tests with the selected browser
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:menu -- --browser=${{ github.event.inputs.browser || 'chrome' }}
      
      # Step 5: Upload screenshots on failure
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-menu
          path: cypress/screenshots
          if-no-files-found: ignore 
  
  account-test:

    runs-on: ubuntu-latest

    steps:
      
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 3: Configure node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Step 4: Execute tests with the selected browser
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:account -- --browser=${{ github.event.inputs.browser || 'chrome' }}
          
      # Step 5: Upload screenshots on failure
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-account
          path: cypress/screenshots
          if-no-files-found: ignore 