name: End-to-end tests

on: 

  pull_request: 
    branches:
      - '**'
      
  push:
    branches:
      - '**' 

  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: "Qual navegador você vai realizar os testes"
        required: true
        options:
          - chromium
          - chrome
          - firefox
          - edge
          - webkit
          - electron

jobs:

  cypress-run:

    runs-on: ubuntu-latest

    steps:
      
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm ci
      
      # Step 3: Configure node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Step 4: Execute tests with the selected browser
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ inputs.browser }}
      
      # Step 5: Upload screenshots on failure
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 
          
      # Step 6: Upload videos
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore 